sonar.projectKey=vann10_focalboard
sonar.organization=vandalism
sonar.projectName=Focalboard
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/vendor/**,**/*_test.go,**/*.test.ts,**/*.test.tsx
sonar.tests=server,webapp
sonar.test.inclusions=**/*_test.go,**/*.test.ts,**/*.test.tsx

# Go coverage
sonar.go.coverage.reportPaths=server/coverage.out

# JS/TS coverage
sonar.javascript.lcov.reportPaths=webapp/coverage/lcov.info

sonar.sourceEncoding=UTF-8